### ISSUE TITLE
Path issues preventing use on windows

### ISSUE THREAD

**Issue by DanOlds** [maffettone/xca#1]
Running simple_example.py on Windows 10 runs for a bit, then crashes out.
```

C:\Users\dolds\Anaconda3\envs\xca\lib\site-packages\xca\examples\arxiv200800283\cifs-BaTiO\cubic.cif
C:\Users\dolds\Anaconda3\envs\xca\lib\site-packages\xca\examples\arxiv200800283\cifs-BaTiO\ortho.cif
C:\Users\dolds\Anaconda3\envs\xca\lib\site-packages\xca\examples\arxiv200800283\cifs-BaTiO\rhomb.cif
C:\Users\dolds\Anaconda3\envs\xca\lib\site-packages\xca\examples\arxiv200800283\cifs-BaTiO\tetra.cif
Traceback (most recent call last):
  File ".\simple_example.py", line 19, in <module>
    main()
  File ".\simple_example.py", line 10, in main
    dir2TFR(f"tmp/{system}", f"tmp/{system}.tfrecords")
  File "C:\Users\dolds\Anaconda3\envs\xca\lib\site-packages\xca\ml\tf_data_proc.py", line 27, in dir2TFR
    label = str(fname).split('/')[-2]
IndexError: list index out of range

```

**Comment by maffettone** [comment]
Try pulling this branch and re-running the examples in the readme. Simple example will be quick to run and should hit on many of the issues in path management. 

https://github.com/maffettone/xca/tree/pathlib
